# configuration for https://ohi-science.nceas.ucsb.edu/ohi-global
study_area:       
git_owner:        OHI-Science
git_repo:         ohi-global
git_slug:         OHI-Science/ohi-global
git_url:          https://github.com/OHI-Science/ohi-global
app_url:          http://ohi-science.nceas.ucsb.edu/ohi-global
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2015-04-07
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: d3cf86f2594fb97b034c8dfb8bd84f6d6171a740

tabs_hide:        
- Calculate
- Report

